### ISSUE TITLE
App mit GitHub Action auf Azure Portal publishen

### ISSUE THREAD

**Issue by tschumpr** [blw-ofag-ufag/geodatenbezug_geodienste#19]
Mit der Github Action von Azure wird der Code nicht korrekt nach Azure Portal hochgeladen, weshalb die Function im Portal nicht korrekt geladen wird.

Relevanter Code: 

- .github/pre-release.yml
- https://github.com/Azure/functions-action

Als Übergangslösung kann der Code via _VS Code > Azure Extension > Workspace > Deploy to Function App_ veröffentlicht werden. Dazu musste im Azure Portal für die App unter _Networking_ _Public Network Access_ enabled werden. Wenn die Github Action funktioniert, kann man das wieder disablen.

**Comment by danjov** [comment]
Der Fehler lag an einer Fehlkonfiguration der _Federated credentials_ der zugewiesenen _Managed Identity_ im Azure Portal. Die Credentials waren auf `Environment`- anstatt `Branch`-Ebene definiert; da das `environment` in der GitHub-Action nicht definiert war, hat das Login nicht funktioniert. Wir haben die _Federated credentials_ nun wieder so konfiguriert, dass der Publish nur auf dem `main`-Branch durchläuft.
